#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload="$(cat <&0)"

dependency=$(jq -r '.source.dependency // ""' <<< "$payload")
repository=$(jq -r '.source.repository // ""' <<< "$payload")

if [[ $dependency == "" ]] || [[ $repository == "" ]]; then
  echo "Dependency or Repository was not specified"
  exit 1
fi

helm repo add repository $repository

version=$(helm search repo repository/$dependency -o json | jq -r '[.[]][0] | .version')

echo "Version: $version"

echo "[ {\"ref\": \"${version}\"} ]" >&3
